PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZRM_DUMVW-DUMID .
    FIELD ZRM_DUMVW-ZRM_NAME .
    FIELD ZRM_DUMVW-ZRM_LNAME .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    MODULE COMPLETE_ZRM_DUMVW ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZRM_DUMVW-DUMID .
  module detail_pai.
 endchain.
