*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZPROJ26_VW......................................*
FORM GET_DATA_ZPROJ26_VW.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTRPROJECT26 WHERE
(VIM_WHERETAB) .
    CLEAR ZPROJ26_VW .
ZPROJ26_VW-MANDT =
ZTRPROJECT26-MANDT .
ZPROJ26_VW-PNO =
ZTRPROJECT26-PNO .
    SELECT SINGLE * FROM ZPD2 WHERE
PNO = ZTRPROJECT26-PNO .
    IF SY-SUBRC EQ 0.
ZPROJ26_VW-PDLOC =
ZPD2-PDLOC .
ZPROJ26_VW-PDESC =
ZPD2-PDESC .
    ENDIF.
<VIM_TOTAL_STRUC> = ZPROJ26_VW.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZPROJ26_VW .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZPROJ26_VW.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZPROJ26_VW-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTRPROJECT26 WHERE
  PNO = ZPROJ26_VW-PNO .
    IF SY-SUBRC = 0.
    DELETE ZTRPROJECT26 .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZPD2 WHERE
    PNO = ZTRPROJECT26-PNO .
    IF SY-SUBRC = 0.
    DELETE ZPD2 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTRPROJECT26 WHERE
  PNO = ZPROJ26_VW-PNO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTRPROJECT26.
    ENDIF.
ZTRPROJECT26-MANDT =
ZPROJ26_VW-MANDT .
ZTRPROJECT26-PNO =
ZPROJ26_VW-PNO .
    IF SY-SUBRC = 0.
    UPDATE ZTRPROJECT26 ##WARN_OK.
    ELSE.
    INSERT ZTRPROJECT26 .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZPD2 WHERE
    PNO = ZTRPROJECT26-PNO .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR ZPD2.
ZPD2-PNO =
ZTRPROJECT26-PNO .
      ENDIF.
ZPD2-PDLOC =
ZPROJ26_VW-PDLOC .
ZPD2-PDESC =
ZPROJ26_VW-PDESC .
    IF SY-SUBRC = 0.
    UPDATE ZPD2 ##WARN_OK.
    ELSE.
    INSERT ZPD2 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZPROJ26_VW-UPD_FLAG,
STATUS_ZPROJ26_VW-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZPROJ26_VW.
  SELECT SINGLE * FROM ZTRPROJECT26 WHERE
PNO = ZPROJ26_VW-PNO .
ZPROJ26_VW-MANDT =
ZTRPROJECT26-MANDT .
ZPROJ26_VW-PNO =
ZTRPROJECT26-PNO .
    SELECT SINGLE * FROM ZPD2 WHERE
PNO = ZTRPROJECT26-PNO .
    IF SY-SUBRC EQ 0.
ZPROJ26_VW-PDLOC =
ZPD2-PDLOC .
ZPROJ26_VW-PDESC =
ZPD2-PDESC .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZPROJ26_VW-PDLOC .
      CLEAR ZPROJ26_VW-PDESC .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZPROJ26_VW USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZPROJ26_VW-PNO TO
ZTRPROJECT26-PNO .
MOVE ZPROJ26_VW-MANDT TO
ZTRPROJECT26-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTRPROJECT26'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTRPROJECT26 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTRPROJECT26'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE ZTRPROJECT26-PNO TO
ZPD2-PNO .
MOVE ZPROJ26_VW-MANDT TO
ZPD2-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZPD2'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZPD2 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZPD2'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZRM_DUMVW.......................................*
FORM GET_DATA_ZRM_DUMVW.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZRM_D1 WHERE
(VIM_WHERETAB) .
    CLEAR ZRM_DUMVW .
ZRM_DUMVW-MANDT =
ZRM_D1-MANDT .
ZRM_DUMVW-DUMID =
ZRM_D1-DUMID .
ZRM_DUMVW-ZRM_NAME =
ZRM_D1-ZRM_NAME .
    SELECT SINGLE * FROM ZRM_D2 WHERE
DUMID = ZRM_D1-DUMID .
    IF SY-SUBRC EQ 0.
ZRM_DUMVW-ZRM_LNAME =
ZRM_D2-ZRM_LNAME .
    ENDIF.
<VIM_TOTAL_STRUC> = ZRM_DUMVW.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZRM_DUMVW .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZRM_DUMVW.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZRM_DUMVW-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZRM_D1 WHERE
  DUMID = ZRM_DUMVW-DUMID .
    IF SY-SUBRC = 0.
    DELETE ZRM_D1 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZRM_D1 WHERE
  DUMID = ZRM_DUMVW-DUMID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZRM_D1.
    ENDIF.
ZRM_D1-MANDT =
ZRM_DUMVW-MANDT .
ZRM_D1-DUMID =
ZRM_DUMVW-DUMID .
ZRM_D1-ZRM_NAME =
ZRM_DUMVW-ZRM_NAME .
    IF SY-SUBRC = 0.
    UPDATE ZRM_D1 ##WARN_OK.
    ELSE.
    INSERT ZRM_D1 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZRM_DUMVW-UPD_FLAG,
STATUS_ZRM_DUMVW-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZRM_DUMVW.
  SELECT SINGLE * FROM ZRM_D1 WHERE
DUMID = ZRM_DUMVW-DUMID .
ZRM_DUMVW-MANDT =
ZRM_D1-MANDT .
ZRM_DUMVW-DUMID =
ZRM_D1-DUMID .
ZRM_DUMVW-ZRM_NAME =
ZRM_D1-ZRM_NAME .
    SELECT SINGLE * FROM ZRM_D2 WHERE
DUMID = ZRM_D1-DUMID .
    IF SY-SUBRC EQ 0.
ZRM_DUMVW-ZRM_LNAME =
ZRM_D2-ZRM_LNAME .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZRM_DUMVW-ZRM_LNAME .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZRM_DUMVW USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZRM_DUMVW-DUMID TO
ZRM_D1-DUMID .
MOVE ZRM_DUMVW-MANDT TO
ZRM_D1-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZRM_D1'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZRM_D1 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZRM_D1'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZRM_DUMVW USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZRM_D1-MANDT =
ZRM_DUMVW-MANDT .
ZRM_D1-DUMID =
ZRM_DUMVW-DUMID .
ZRM_D1-ZRM_NAME =
ZRM_DUMVW-ZRM_NAME .
    SELECT SINGLE * FROM ZRM_D2 WHERE
DUMID = ZRM_D1-DUMID .
    IF SY-SUBRC EQ 0.
ZRM_DUMVW-ZRM_LNAME =
ZRM_D2-ZRM_LNAME .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZRM_DUMVW-ZRM_LNAME .
    ENDIF.
ENDFORM.
*...processing: ZRM_PEOPLEMAINVW................................*
FORM GET_DATA_ZRM_PEOPLEMAINVW.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZRM_PEOPLEINT WHERE
(VIM_WHERETAB) .
    CLEAR ZRM_PEOPLEMAINVW .
ZRM_PEOPLEMAINVW-MANDT =
ZRM_PEOPLEINT-MANDT .
ZRM_PEOPLEMAINVW-PERSONID =
ZRM_PEOPLEINT-PERSONID .
ZRM_PEOPLEMAINVW-INTRESTID =
ZRM_PEOPLEINT-INTRESTID .
ZRM_PEOPLEMAINVW-SKILLLEVEL =
ZRM_PEOPLEINT-SKILLLEVEL .
    SELECT SINGLE * FROM ZRM_INTMASTER WHERE
INTRESTID = ZRM_PEOPLEINT-INTRESTID .
    IF SY-SUBRC EQ 0.
ZRM_PEOPLEMAINVW-INTRESTNAME =
ZRM_INTMASTER-INTRESTNAME .
    ENDIF.
    SELECT SINGLE * FROM ZRM_PERSON WHERE
PERSONID = ZRM_PEOPLEINT-PERSONID .
    IF SY-SUBRC EQ 0.
ZRM_PEOPLEMAINVW-FIRST_NAME =
ZRM_PERSON-FIRST_NAME .
ZRM_PEOPLEMAINVW-LAST_NAME =
ZRM_PERSON-LAST_NAME .
    ENDIF.
<VIM_TOTAL_STRUC> = ZRM_PEOPLEMAINVW.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZRM_PEOPLEMAINVW .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZRM_PEOPLEMAINVW.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZRM_PEOPLEMAINVW-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZRM_PEOPLEINT WHERE
  PERSONID = ZRM_PEOPLEMAINVW-PERSONID AND
  INTRESTID = ZRM_PEOPLEMAINVW-INTRESTID .
    IF SY-SUBRC = 0.
    DELETE ZRM_PEOPLEINT .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZRM_PEOPLEINT WHERE
  PERSONID = ZRM_PEOPLEMAINVW-PERSONID AND
  INTRESTID = ZRM_PEOPLEMAINVW-INTRESTID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZRM_PEOPLEINT.
    ENDIF.
ZRM_PEOPLEINT-MANDT =
ZRM_PEOPLEMAINVW-MANDT .
ZRM_PEOPLEINT-PERSONID =
ZRM_PEOPLEMAINVW-PERSONID .
ZRM_PEOPLEINT-INTRESTID =
ZRM_PEOPLEMAINVW-INTRESTID .
ZRM_PEOPLEINT-SKILLLEVEL =
ZRM_PEOPLEMAINVW-SKILLLEVEL .
    IF SY-SUBRC = 0.
    UPDATE ZRM_PEOPLEINT ##WARN_OK.
    ELSE.
    INSERT ZRM_PEOPLEINT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZRM_PEOPLEMAINVW-UPD_FLAG,
STATUS_ZRM_PEOPLEMAINVW-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZRM_PEOPLEMAINVW.
  SELECT SINGLE * FROM ZRM_PEOPLEINT WHERE
PERSONID = ZRM_PEOPLEMAINVW-PERSONID AND
INTRESTID = ZRM_PEOPLEMAINVW-INTRESTID .
ZRM_PEOPLEMAINVW-MANDT =
ZRM_PEOPLEINT-MANDT .
ZRM_PEOPLEMAINVW-PERSONID =
ZRM_PEOPLEINT-PERSONID .
ZRM_PEOPLEMAINVW-INTRESTID =
ZRM_PEOPLEINT-INTRESTID .
ZRM_PEOPLEMAINVW-SKILLLEVEL =
ZRM_PEOPLEINT-SKILLLEVEL .
    SELECT SINGLE * FROM ZRM_INTMASTER WHERE
INTRESTID = ZRM_PEOPLEINT-INTRESTID .
    IF SY-SUBRC EQ 0.
ZRM_PEOPLEMAINVW-INTRESTNAME =
ZRM_INTMASTER-INTRESTNAME .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZRM_PEOPLEMAINVW-INTRESTNAME .
    ENDIF.
    SELECT SINGLE * FROM ZRM_PERSON WHERE
PERSONID = ZRM_PEOPLEINT-PERSONID .
    IF SY-SUBRC EQ 0.
ZRM_PEOPLEMAINVW-FIRST_NAME =
ZRM_PERSON-FIRST_NAME .
ZRM_PEOPLEMAINVW-LAST_NAME =
ZRM_PERSON-LAST_NAME .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZRM_PEOPLEMAINVW-FIRST_NAME .
      CLEAR ZRM_PEOPLEMAINVW-LAST_NAME .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZRM_PEOPLEMAINVW USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZRM_PEOPLEMAINVW-PERSONID TO
ZRM_PEOPLEINT-PERSONID .
MOVE ZRM_PEOPLEMAINVW-INTRESTID TO
ZRM_PEOPLEINT-INTRESTID .
MOVE ZRM_PEOPLEMAINVW-MANDT TO
ZRM_PEOPLEINT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZRM_PEOPLEINT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZRM_PEOPLEINT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZRM_PEOPLEINT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZRM_PEOPLEMAINVW USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZRM_PEOPLEINT-MANDT =
ZRM_PEOPLEMAINVW-MANDT .
ZRM_PEOPLEINT-PERSONID =
ZRM_PEOPLEMAINVW-PERSONID .
ZRM_PEOPLEINT-INTRESTID =
ZRM_PEOPLEMAINVW-INTRESTID .
ZRM_PEOPLEINT-SKILLLEVEL =
ZRM_PEOPLEMAINVW-SKILLLEVEL .
    SELECT SINGLE * FROM ZRM_INTMASTER WHERE
INTRESTID = ZRM_PEOPLEINT-INTRESTID .
    IF SY-SUBRC EQ 0.
ZRM_PEOPLEMAINVW-INTRESTNAME =
ZRM_INTMASTER-INTRESTNAME .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZRM_PEOPLEMAINVW-INTRESTNAME .
    ENDIF.
    SELECT SINGLE * FROM ZRM_PERSON WHERE
PERSONID = ZRM_PEOPLEINT-PERSONID .
    IF SY-SUBRC EQ 0.
ZRM_PEOPLEMAINVW-FIRST_NAME =
ZRM_PERSON-FIRST_NAME .
ZRM_PEOPLEMAINVW-LAST_NAME =
ZRM_PERSON-LAST_NAME .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZRM_PEOPLEMAINVW-FIRST_NAME .
      CLEAR ZRM_PEOPLEMAINVW-LAST_NAME .
    ENDIF.
ENDFORM.

* base table related FORM-routines.............
INCLUDE LSVIMFTX .
