PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZRMDUMMYMAINT CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZRMDUMMYMAINT-PERSONID .
    FIELD ZRMDUMMYMAINT-INTRESTID .
    FIELD ZRMDUMMYMAINT-FIRST_NAME .
    FIELD ZRMDUMMYMAINT-LAST_NAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    MODULE COMPLETE_ZRMDUMMYMAINT ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZRMDUMMYMAINT-PERSONID .
    FIELD ZRMDUMMYMAINT-INTRESTID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
