PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZRMDUMMYMAINT-PERSONID .
    FIELD ZRMDUMMYMAINT-INTRESTID .
    FIELD ZRMDUMMYMAINT-FIRST_NAME .
    FIELD ZRMDUMMYMAINT-LAST_NAME .
    FIELD ZRMDUMMYMAINT-DOB .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    MODULE COMPLETE_ZRMDUMMYMAINT ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZRMDUMMYMAINT-PERSONID .
    FIELD ZRMDUMMYMAINT-INTRESTID .
  module detail_pai.
 endchain.
