PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZRM_ORDERHEADER-ORDERNO .
    FIELD ZRM_ORDERHEADER-ORDERDATE .
    FIELD ZRM_ORDERHEADER-CUSTOMER_ID .
    FIELD ZRM_ORDERHEADER-TOV .
    FIELD ZRM_ORDERHEADER-CREATED_BY .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZRM_ORDERHEADER-ORDERNO .
  module detail_pai.
 endchain.
