PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZRM_T4_ANIME-ANIME_ID .
    FIELD ZRM_T4_ANIME-ANIME_NAME .
    FIELD ZRM_T4_ANIME-ANIME_RATING .
    FIELD ZRM_T4_ANIME-MANGA_COST .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZRM_T4_ANIME-ANIME_ID .
  module detail_pai.
 endchain.
