PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZRM_T2_FRIENDS-ID .
    FIELD ZRM_T2_FRIENDS-FIRST_NAME .
    FIELD ZRM_T2_FRIENDS-UDDHAR .
    FIELD ZRM_T2_FRIENDS-UUDHAR_UNIT .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZRM_T2_FRIENDS-ID .
  module detail_pai.
 endchain.
