PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZRM_MAINTVW-ITEMORDER .
    FIELD ZRM_MAINTVW-ORDERNO .
    FIELD ZRM_MAINTVW-TOV .
    FIELD ZRM_MAINTVW-CREATED_BY .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    MODULE COMPLETE_ZRM_MAINTVW ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZRM_MAINTVW-ITEMORDER .
    FIELD ZRM_MAINTVW-ORDERNO .
  module detail_pai.
 endchain.
