*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZRM_MAINTVW.....................................*
FORM GET_DATA_ZRM_MAINTVW.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZRM_ITEMTABLE WHERE
(VIM_WHERETAB) .
    CLEAR ZRM_MAINTVW .
ZRM_MAINTVW-MANDT =
ZRM_ITEMTABLE-MANDT .
ZRM_MAINTVW-ITEMORDER =
ZRM_ITEMTABLE-ITEMORDER .
    SELECT SINGLE * FROM ZRM_ORDERHEADER WHERE
ORDERNO = ZRM_ITEMTABLE-ITEMORDER .
    IF SY-SUBRC EQ 0.
ZRM_MAINTVW-ORDERNO =
ZRM_ORDERHEADER-ORDERNO .
ZRM_MAINTVW-TOV =
ZRM_ORDERHEADER-TOV .
ZRM_MAINTVW-CREATED_BY =
ZRM_ORDERHEADER-CREATED_BY .
    ENDIF.
<VIM_TOTAL_STRUC> = ZRM_MAINTVW.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZRM_MAINTVW .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZRM_MAINTVW.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZRM_MAINTVW-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZRM_ITEMTABLE WHERE
  ITEMORDER = ZRM_MAINTVW-ITEMORDER .
    IF SY-SUBRC = 0.
    DELETE ZRM_ITEMTABLE .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZRM_ITEMTABLE WHERE
  ITEMORDER = ZRM_MAINTVW-ITEMORDER .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZRM_ITEMTABLE.
    ENDIF.
ZRM_ITEMTABLE-MANDT =
ZRM_MAINTVW-MANDT .
ZRM_ITEMTABLE-ITEMORDER =
ZRM_MAINTVW-ITEMORDER .
    IF SY-SUBRC = 0.
    UPDATE ZRM_ITEMTABLE ##WARN_OK.
    ELSE.
    INSERT ZRM_ITEMTABLE .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZRM_MAINTVW-UPD_FLAG,
STATUS_ZRM_MAINTVW-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZRM_MAINTVW.
  SELECT SINGLE * FROM ZRM_ITEMTABLE WHERE
ITEMORDER = ZRM_MAINTVW-ITEMORDER .
ZRM_MAINTVW-MANDT =
ZRM_ITEMTABLE-MANDT .
ZRM_MAINTVW-ITEMORDER =
ZRM_ITEMTABLE-ITEMORDER .
    SELECT SINGLE * FROM ZRM_ORDERHEADER WHERE
ORDERNO = ZRM_ITEMTABLE-ITEMORDER .
    IF SY-SUBRC EQ 0.
ZRM_MAINTVW-ORDERNO =
ZRM_ORDERHEADER-ORDERNO .
ZRM_MAINTVW-TOV =
ZRM_ORDERHEADER-TOV .
ZRM_MAINTVW-CREATED_BY =
ZRM_ORDERHEADER-CREATED_BY .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZRM_MAINTVW-ORDERNO .
      CLEAR ZRM_MAINTVW-TOV .
      CLEAR ZRM_MAINTVW-CREATED_BY .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZRM_MAINTVW USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZRM_MAINTVW-ITEMORDER TO
ZRM_ITEMTABLE-ITEMORDER .
MOVE ZRM_MAINTVW-MANDT TO
ZRM_ITEMTABLE-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZRM_ITEMTABLE'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZRM_ITEMTABLE TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZRM_ITEMTABLE'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZRM_MAINTVW USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZRM_ITEMTABLE-MANDT =
ZRM_MAINTVW-MANDT .
ZRM_ITEMTABLE-ITEMORDER =
ZRM_MAINTVW-ITEMORDER .
    SELECT SINGLE * FROM ZRM_ORDERHEADER WHERE
ORDERNO = ZRM_ITEMTABLE-ITEMORDER .
    IF SY-SUBRC EQ 0.
ZRM_MAINTVW-ORDERNO =
ZRM_ORDERHEADER-ORDERNO .
ZRM_MAINTVW-TOV =
ZRM_ORDERHEADER-TOV .
ZRM_MAINTVW-CREATED_BY =
ZRM_ORDERHEADER-CREATED_BY .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZRM_MAINTVW-ORDERNO .
      CLEAR ZRM_MAINTVW-TOV .
      CLEAR ZRM_MAINTVW-CREATED_BY .
    ENDIF.
ENDFORM.
