PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZRM_PEOPLEMAINVW CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZRM_PEOPLEMAINVW-PERSONID .
    FIELD ZRM_PEOPLEMAINVW-INTRESTID .
    FIELD ZRM_PEOPLEMAINVW-INTRESTNAME .
    FIELD ZRM_PEOPLEMAINVW-FIRST_NAME .
    FIELD ZRM_PEOPLEMAINVW-LAST_NAME .
    FIELD ZRM_PEOPLEMAINVW-SKILLLEVEL .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    MODULE COMPLETE_ZRM_PEOPLEMAINVW ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZRM_PEOPLEMAINVW-PERSONID .
    FIELD ZRM_PEOPLEMAINVW-INTRESTID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
